version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: ytdownloader:v1
    container_name: app_ytdownloader
    command: python3 manage.py runserver 0.0.0.0:8000
